apiVersion: v1
kind: Pod
metadata:
  name: csi-rbd-test-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: rbd-data
          mountPath: /data
  volumes:
    - name: rbd-data
      persistentVolumeClaim:
        claimName: rbd-pvc
